### ISSUE TITLE
[Bug Report] Cant login with default user

### ISSUE THREAD

**Issue by Okashichan** [hkalexling/Mango#127]
**Describe the bug**
When Im try to login with defaults (admin:password), page just refreshes and the log empty. But, for example, when I try to login with some not existing user I have an error in the log: "[ERROR]   2020/12/09 15:29:20 | Error when verifying user nonexistentuser: no results". Its kinda weird.

**To Reproduce**
1. Install mango 0.16.0
2. Login

**Expected behavior**
Login in

**Environment (please complete the following information):**
 - OS: OpenMediaVault (5.5.11-1 (Usul))
 - Browser: Google Chrome, Microsoft Edge
 - Mango Version: 0.16.0

**Docker container**
```
version: '2'

services:
  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9000
    ports:
      - 9001:9000
    volumes:
      - /srv/dev-disk-by-id-ata-WDC_WD10SPZX-00Z10T0_WD-WXK1AC9N84F5-part1/Mango:/root/mango
      - /srv/dev-disk-by-id-ata-WDC_WD10SPZX-00Z10T0_WD-WXK1AC9N84F5-part1/Config/mango:/root/.config/mango
```

**Additional context**
Port 9000 already in use by the Portainer, that why 9001:9000.
