### ISSUE TITLE
[Feature Request] restrict image height in continuous reader

### ISSUE THREAD

**Issue by Leeingnyo** [hkalexling/Mango#152]
Some scanned comics files have its book spine. Their ratio is so odd and unbalanced (for example, some book has 22(W) x 3000(H) spine image).
In the continuous reader, its width fits the screen (max 900px) and the height of example spine image becomes 122,727px, showing nearly endless purple image. https://imgur.com/a/vlavZKA

I tried to resolve this by adding following style temporarily.

```css
img[uk-img] {
    height: auto;
    width: auto;
    max-height: 2000px; /* if removed, images have their original height */
}
```

This style restricted the height of image well and preserved its ratio, but caused another problem:
If the manga image has smaller width than 900px, it has its original width, not fitting the screen anymore.
The reader would not have unified image widths

![image](https://user-images.githubusercontent.com/6760150/105882839-7b278a00-6049-11eb-8318-6eb56d0ee5f9.png)
**Fig 01.** the width of small image has its original size (850px)

Let me know about your opinion!

-----

Saying shortly, I want to restrict too long height of the unbalanced image to reasonable height.
