### ISSUE TITLE
[Question] Kubernetes setup - 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by dqle** [hkalexling/Mango#165]
Below is my yaml setup in my kubernetes cluster:

Deployment.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-mango-mango
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-mango-mango
    spec:
      containers:
        - image: 'hkalexling/mango:v0.20.0'
          imagePullPolicy: IfNotPresent
          name: mango
          ports:
            - containerPort: 9000
              name: mango-port
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/mango/library
              name: ebooks-library
            - mountPath: /root/.config/mango
              name: mango-config
            - mountPath: /root/mango
              name: mango-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ebooks-library
          nfs:
            path: /ebooks-library/Manga
            server: 10.10.0.10
        - name: mango-config
          nfs:
            path: /k8s-app-config/mango
            server: 10.10.0.10
```

service.yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: mango-service
  namespace: mango
spec:
  clusterIP: 10.43.183.121
  externalTrafficPolicy: Cluster
  ports:
  - name: mango-port
    nodePort: 31550
    port: 80
    protocol: TCP
    targetPort: 9000
  sessionAffinity: None
  type: NodePort
```

Ingress.yaml:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mango-ingress
  namespace: mango
spec:
  rules:
    - host: mango.example.com
      http:
        paths:
          - backend:
              service:
                name: mango-service
                port:
                  number: 80
            path: /
            pathType: Prefix
```

I then add mango.example.com to my DNS pointing to the node's ip address. However, when hitting it, all I got is 503 Service Temporarily Unavailable nginx/1.19.2 returned from the pod.

I've done this same setup for a few other application in my cluster and they're working fine. Not sure if I have something odd in my setup. Any help would be appreciated!
