### ISSUE TITLE
MangaDex API Redirection

### ISSUE THREAD

**Issue by B17C0D3** [hkalexling/Mango#174]
**Describe the bug**
The screenshot is kinda obvious. i will skimp the details.
![image](https://user-images.githubusercontent.com/3804141/110479655-ed2dcd00-80e5-11eb-8ac0-eadc50292a54.png)

I get this bug since yesterday the 2021-03-08.
Mangadex had again some DDOS attacks und may have done some changes.

API address may have to be changed to https://api.mangadex.org/v2/ ??

**Comment by hkalexling** [comment]
Thanks for letting me know. According to the devs on the MD Discord, it is recommended to use the new https://api.mangadex.org/v2. Currently they redirect requests from https://mangadex.org/api/v2 to the new one, but they would stop the redirection in a few days. 

You can simply change the `api_url` field in your config file to `https://api.mangadex.org/v2`. In the up coming release, this will be the default value.

**Comment by Nerothos** [comment]
I'm reopening this because I did the url change but I got this message : 

```Failed to get manga info. Error: Failed to parse JSON```

**Comment by hkalexling** [comment]
@Nerothos I couldn't reproduce this. Would be great if you could paste your config and let me know what you did before seeing the error.

**Comment by Nerothos** [comment]
Here's the config : (it's the one from the container so I'm sure it's the applied one)
```
port: 9000
base_url: /
session_secret: mango-session-secret
library_path: /root/mango/library
db_path: /root/mango/mango.db
scan_interval_minutes: 5
thumbnail_generation_interval_hours: 24
log_level: info
upload_path: /root/mango/uploads
plugin_path: /root/mango/plugins
download_timeout_seconds: 30
page_margin: 30
disable_login: false
default_username: ""
mangadex:
  base_url: https://mangadex.org
  api_url: https://api.mangadex.org/v2
  download_wait_seconds: 5
  download_retries: 4
  download_queue_db_path: /root/mango/queue.db
  chapter_rename_rule: '[Vol.{volume} ][Ch.{chapter} ]{title|id}'
  manga_rename_rule: '{title}'
```
