### ISSUE TITLE
[Bug Report] Continue Reading doesnt work

### ISSUE THREAD

**Issue by Joinatic** [hkalexling/Mango#98]
**Describe the bug**
When clicking on continue reading it starts from the beginning instead of jumping to the page where I left it.

**To Reproduce**
1. Go to a book (in my example cbz)
2. Start reading it to a random point
3. go back to library
4. click the book again
5. click continue reading
6. see it starts from page 1 instead of page X

**Expected behavior**
Continue where I left.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: chrome and firefox
 - Mango Version: 0.11.0
 - Docker: 19.03.12, build 48a66213fe

**Docker (if you are running Mango in a Docker container)**
```
 mango:
    image: hkalexling/mango:v0.11.0
    container_name: mango
    restart: always
    labels: 
      - traefik.enable=true
      - "traefik.web.frontend.rule=Host:my.domain"
      - traefik.web.port=9000
    volumes:
      - /var/docker/mango/root:/root/mango
      - /var/docker/mango/config:/root/.config/mango
      - /media/animeMO/Manga:/root/mango/library
    networks:
      - onubuntu
```
